name: Deploy to Vercel

on:
  push:
    branches:
      - main   # Deploy only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'   # or your project version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build project
      - name: Build project
        run: npm run build

      # Deploy to Vercel
      - name: Deploy
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
